apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.appName }}-{{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: {{ .Values.clusterRoleBinding.apiGroup }}
  kind: ClusterRole
  name: {{ .Values.clusterRoleBinding.name }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.namespace }}
