apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host:  {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}
                port:
                  number: {{ .Values.ingress.port }}
