namespace: prod
appName: gift-certificates
deployment:
  replicaCount: 1
  label: gift-certificates
  container:
    name: gift-certificates
    image: image
    imagePullPolicy: IfNotPresent
    httpPort: 8080
volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
volumeMounts:
  - name: secret-volume
    readOnly: true
    mountPath: /var/gift-certificates/application.properties
    subPath: application.properties
clusterRoleBinding:
 apiGroup: rbac.authorization.k8s.io
 name: cluster-admin-prod
ingress:
  ingressClassName: nginx
  host: gift-certificates.k8s-3.sa
  port: 8080
service:
  port: 8080
secret:
  name: secret
